# Generated by Django 4.2.27 on 2026-03-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0018_add_safety_stock_and_reserved_stock'),
        ('printing', '0002_add_carrier_stub'),
        ('clients', '0004_add_wms_fields_and_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_order_id', models.CharField(max_length=30, unique=True, verbose_name='WMS주문번호')),
                ('source', models.CharField(max_length=30, verbose_name='주문출처')),
                ('source_order_id', models.CharField(db_index=True, max_length=100, verbose_name='원본주문번호')),
                ('order_type', models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B')], default='B2C', max_length=10, verbose_name='주문유형')),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('ALLOCATED', '할당완료'), ('PICKING', '피킹중'), ('INSPECTED', '검수완료'), ('SHIPPED', '출고완료'), ('HELD', '보류'), ('CANCELLED', '취소')], default='RECEIVED', max_length=20, verbose_name='상태')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수취인')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('recipient_address', models.TextField(verbose_name='배송지')),
                ('recipient_zip', models.CharField(blank=True, default='', max_length=10, verbose_name='우편번호')),
                ('shipping_memo', models.TextField(blank=True, default='', verbose_name='배송메모')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=50, verbose_name='송장번호')),
                ('hold_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='보류사유')),
                ('ordered_at', models.DateTimeField(verbose_name='주문일시')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='출고일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_orders', to='clients.brand', verbose_name='브랜드')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.carrier', verbose_name='택배사')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_orders', to='clients.client', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '출고주문',
                'verbose_name_plural': '출고주문',
                'db_table': 'outbound_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_id', models.CharField(max_length=30, unique=True, verbose_name='웨이브번호')),
                ('status', models.CharField(choices=[('CREATED', '생성'), ('PICKING', '피킹중'), ('COMPLETED', '완료')], default='CREATED', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '웨이브',
                'verbose_name_plural': '웨이브',
                'db_table': 'waves',
            },
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='주문수량')),
                ('picked_qty', models.IntegerField(default=0, verbose_name='피킹수량')),
                ('inspected_qty', models.IntegerField(default=0, verbose_name='검수수량')),
                ('source_item_id', models.CharField(blank=True, default='', max_length=100, verbose_name='원본품목ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waves.outboundorder', verbose_name='출고주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_items', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '출고주문 품목',
                'verbose_name_plural': '출고주문 품목',
                'db_table': 'outbound_order_items',
            },
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='waves.wave', verbose_name='웨이브'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['client', 'status'], name='idx_outbound_client_status'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['wave'], name='idx_outbound_wave'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['source', 'source_order_id'], name='idx_outbound_source'),
        ),
    ]
