# Generated by Django 4.2.27 on 2026-03-04 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_safety_stock_and_reserved_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waves', '0001_create_outbound_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField(verbose_name='합산수량')),
                ('picked_qty', models.IntegerField(default=0, verbose_name='피킹수량')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '토탈피킹 리스트',
                'verbose_name_plural': '토탈피킹 리스트',
                'db_table': 'total_pick_lists',
            },
        ),
        migrations.AlterModelOptions(
            name='wave',
            options={'ordering': ['-created_at'], 'verbose_name': '웨이브', 'verbose_name_plural': '웨이브'},
        ),
        migrations.AddField(
            model_name='wave',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료일시'),
        ),
        migrations.AddField(
            model_name='wave',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='wave',
            name='inspected_count',
            field=models.IntegerField(default=0, verbose_name='검수완료 주문수'),
        ),
        migrations.AddField(
            model_name='wave',
            name='outbound_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='출고존'),
        ),
        migrations.AddField(
            model_name='wave',
            name='picked_count',
            field=models.IntegerField(default=0, verbose_name='피킹완료 주문수'),
        ),
        migrations.AddField(
            model_name='wave',
            name='shipped_count',
            field=models.IntegerField(default=0, verbose_name='출고완료 주문수'),
        ),
        migrations.AddField(
            model_name='wave',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='총 주문수'),
        ),
        migrations.AddField(
            model_name='wave',
            name='total_skus',
            field=models.IntegerField(default=0, verbose_name='총 SKU수'),
        ),
        migrations.AddField(
            model_name='wave',
            name='wave_time',
            field=models.CharField(default='', max_length=5, verbose_name='웨이브 시간'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='status',
            field=models.CharField(choices=[('CREATED', '생성'), ('PICKING', '피킹중'), ('DISTRIBUTING', '분배중'), ('SHIPPING', '출고중'), ('COMPLETED', '완료')], default='CREATED', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='wave_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='웨이브번호'),
        ),
        migrations.CreateModel(
            name='TotalPickListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='수량')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='피킹일시')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.location', verbose_name='출발 로케이션')),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='waves.totalpicklist', verbose_name='피킹리스트')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='피킹 작업자')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location', verbose_name='도착 로케이션')),
            ],
            options={
                'verbose_name': '토탈피킹 상세',
                'verbose_name_plural': '토탈피킹 상세',
                'db_table': 'total_pick_list_details',
            },
        ),
        migrations.AddField(
            model_name='totalpicklist',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_lists', to='waves.wave', verbose_name='웨이브'),
        ),
    ]
