# Generated by Django 4.2.27 on 2026-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0002_expand_wave_and_pick_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpicklistdetail',
            name='picked_qty',
            field=models.IntegerField(default=0, verbose_name='피킹수량'),
        ),
    ]
