# Generated by Django 4.2.27 on 2026-01-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': '이미 등록된 이메일 주소입니다.'}, max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('client', '거래처'), ('worker', '작업자')], default='worker', max_length=20, verbose_name='역할')),
                ('is_active', models.BooleanField(default=True, help_text='계정 활성화 여부. 비활성화하면 로그인이 불가능합니다.', verbose_name='활성 상태')),
                ('is_staff', models.BooleanField(default=False, help_text='관리자 사이트 접근 권한', verbose_name='스태프 권한')),
                ('is_approved', models.BooleanField(default=False, help_text='관리자 승인 여부. 승인되지 않으면 로그인이 불가능합니다.', verbose_name='승인 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-created_at'],
            },
        ),
    ]
