# Generated by Django 4.2.27 on 2026-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_pricecontract_uq_price_contract_client_type_from_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='users', to='clients.client', verbose_name='소속 거래처'),
        ),
    ]
