# Generated by Django 4.2.27 on 2026-03-04 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_create_printer_stub'),
        ('accounts', '0004_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('client', '거래처'), ('office', '오피스팀'), ('field', '필드팀'), ('worker', '작업자')], default='worker', max_length=20, verbose_name='역할'),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pda_device_id', models.CharField(blank=True, default='', max_length=100, verbose_name='PDA 기기 ID')),
                ('assigned_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workers', to='printing.printer', verbose_name='할당 프린터')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '작업자 프로필',
                'verbose_name_plural': '작업자 프로필',
                'db_table': 'accounts_worker_profiles',
            },
        ),
    ]
