# Generated by Django 4.2.27 on 2026-03-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_role_office_field_and_worker_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='설정 키')),
                ('value', models.JSONField(verbose_name='설정 값')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정',
                'db_table': 'system_configs',
            },
        ),
    ]
