# Generated by Django 4.2.27 on 2026-03-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_announcement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('all', '전체'), ('internal', '내부 (관리자/작업자)'), ('client', '거래처')], default='all', max_length=20, verbose_name='대상'),
        ),
    ]
