# Generated by Django 4.2.27 on 2026-03-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_add_wms_fields_and_config'),
        ('waves', '0003_add_picked_qty_to_detail'),
        ('inventory', '0018_add_safety_stock_and_reserved_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='반품번호')),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('INSPECTING', '검수중'), ('COMPLETED', '완료')], default='RECEIVED', max_length=20, verbose_name='상태')),
                ('return_reason', models.CharField(choices=[('CUSTOMER_CHANGE', '고객변심'), ('DEFECT', '불량'), ('WRONG_DELIVERY', '오배송'), ('OTHER', '기타')], max_length=20, verbose_name='반품사유')),
                ('notes', models.TextField(blank=True, default='', verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='clients.brand', verbose_name='브랜드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('original_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='waves.outboundorder', verbose_name='원주문')),
            ],
            options={
                'verbose_name': '반품주문',
                'verbose_name_plural': '반품주문',
                'db_table': 'return_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='반품수량')),
                ('good_qty', models.IntegerField(default=0, verbose_name='양품수량')),
                ('defect_qty', models.IntegerField(default=0, verbose_name='불량수량')),
                ('disposition', models.CharField(blank=True, choices=[('RESTOCK', '재입고'), ('DEFECT_ZONE', '불량존'), ('DISPOSE', '폐기')], default='', max_length=20, verbose_name='처리방식')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='inventory.product', verbose_name='상품')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnorder', verbose_name='반품주문')),
            ],
            options={
                'verbose_name': '반품주문 품목',
                'verbose_name_plural': '반품주문 품목',
                'db_table': 'return_order_items',
            },
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['client', 'status'], name='idx_return_client_status'),
        ),
    ]
