# Generated by Django 4.2.27 on 2026-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_create_printer_stub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='택배사명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='택배사 코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '택배사',
                'verbose_name_plural': '택배사 목록',
                'db_table': 'carriers',
            },
        ),
    ]
