# Generated by Django 4.2.27 on 2026-03-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waves', '0003_add_picked_qty_to_detail'),
        ('printing', '0002_add_carrier_stub'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='api_config',
            field=models.JSONField(default=dict, verbose_name='API 설정'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='label_template',
            field=models.TextField(blank=True, default='', verbose_name='라벨 템플릿'),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP 주소'),
        ),
        migrations.AddField(
            model_name='printer',
            name='location_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='설치 위치'),
        ),
        migrations.AddField(
            model_name='printer',
            name='port',
            field=models.IntegerField(default=9100, verbose_name='포트'),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_language',
            field=models.CharField(choices=[('ZPL', 'ZPL'), ('SBPL', 'SBPL'), ('TSPL', 'TSPL')], default='ZPL', max_length=10, verbose_name='프린터 언어'),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('ZEBRA', 'Zebra'), ('SATO', 'SATO'), ('TSC', 'TSC')], default='ZEBRA', max_length=10, verbose_name='프린터 유형'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=50, verbose_name='택배사명'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='송장번호')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('PRINTED', '출력완료'), ('FAILED', '실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('attempts', models.IntegerField(default=0, verbose_name='시도 횟수')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='출력일시')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.carrier', verbose_name='택배사')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='waves.outboundorder', verbose_name='출고주문')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='출력자')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printing.printer', verbose_name='프린터')),
            ],
            options={
                'verbose_name': '출력 작업',
                'verbose_name_plural': '출력 작업 목록',
                'db_table': 'print_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
