# Generated by Django 4.2.27 on 2026-03-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0018_add_safety_stock_and_reserved_stock'),
        ('clients', '0004_add_wms_fields_and_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='입고번호')),
                ('status', models.CharField(choices=[('PLANNED', '예정'), ('ARRIVED', '도착'), ('INSPECTING', '검수중'), ('INSPECTED', '검수완료'), ('PUTAWAY_COMPLETE', '적치완료')], default='PLANNED', max_length=20, verbose_name='상태')),
                ('expected_date', models.DateField(verbose_name='입고예정일')),
                ('notes', models.TextField(blank=True, default='', verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_orders', to='clients.brand', verbose_name='브랜드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_orders', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '입고예정',
                'verbose_name_plural': '입고예정',
                'db_table': 'inbound_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField(verbose_name='예정수량')),
                ('inspected_qty', models.IntegerField(default=0, verbose_name='검수수량')),
                ('defect_qty', models.IntegerField(default=0, verbose_name='불량수량')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='로트번호')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유통기한')),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inbound.inboundorder', verbose_name='입고예정')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_items', to='inventory.product', verbose_name='상품')),
                ('putaway_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_items', to='inventory.location', verbose_name='적치 로케이션')),
            ],
            options={
                'verbose_name': '입고예정 품목',
                'verbose_name_plural': '입고예정 품목',
                'db_table': 'inbound_order_items',
            },
        ),
        migrations.AddIndex(
            model_name='inboundorder',
            index=models.Index(fields=['client', 'status'], name='idx_inbound_client_status'),
        ),
        migrations.AddIndex(
            model_name='inboundorder',
            index=models.Index(fields=['expected_date'], name='idx_inbound_expected_date'),
        ),
    ]
