# Generated by Django 4.2.27 on 2026-03-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구독자명')),
                ('url', models.URLField(verbose_name='수신 URL')),
                ('events', models.JSONField(default=list, verbose_name='구독 이벤트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('secret_key', models.CharField(blank=True, default='', max_length=200, verbose_name='서명 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '웹훅 구독자',
                'verbose_name_plural': '웹훅 구독자',
                'db_table': 'webhook_subscribers',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, verbose_name='이벤트')),
                ('payload', models.JSONField(verbose_name='페이로드')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='응답코드')),
                ('attempts', models.IntegerField(default=0, verbose_name='시도횟수')),
                ('success', models.BooleanField(default=False, verbose_name='성공')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhooks.webhooksubscriber', verbose_name='구독자')),
            ],
            options={
                'verbose_name': '웹훅 로그',
                'verbose_name_plural': '웹훅 로그',
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
