# Generated by Django 4.2.27 on 2026-02-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='세션명')),
                ('status', models.CharField(choices=[('active', '진행중'), ('closed', '종료')], default='active', max_length=10, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일시')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('started_by', models.CharField(blank=True, default='', max_length=50, verbose_name='시작자')),
            ],
            options={
                'verbose_name': '재고조사 세션',
                'verbose_name_plural': '재고조사 세션 목록',
                'db_table': 'inventory_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='로케이션 바코드')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='로케이션명')),
                ('zone', models.CharField(blank=True, default='', max_length=50, verbose_name='구역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '로케이션',
                'verbose_name_plural': '로케이션 목록',
                'db_table': 'locations',
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, verbose_name='상품바코드')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='상품명')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('worker', models.CharField(blank=True, default='', max_length=50, verbose_name='작업자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.location', verbose_name='로케이션')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.inventorysession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '재고 기록',
                'verbose_name_plural': '재고 기록 목록',
                'db_table': 'inventory_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['barcode'], name='inventory_r_barcode_79c384_idx'), models.Index(fields=['session', 'location'], name='inventory_r_session_a974d9_idx')],
            },
        ),
    ]
