# Generated by Django 4.2.27 on 2026-02-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='관리명'),
        ),
    ]
