# Generated by Django 4.2.27 on 2026-02-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, verbose_name='바코드'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('barcode', 'name')},
        ),
    ]
