# Generated by Django 4.2.27 on 2026-02-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_barcode_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='expiry_date',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='유통기한'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='lot_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='로트번호'),
        ),
    ]
