# Generated by Django 4.2.27 on 2026-02-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_inventoryrecord_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='입고수량')),
                ('expiry_date', models.CharField(blank=True, default='', max_length=20, verbose_name='유통기한')),
                ('lot_number', models.CharField(blank=True, default='', max_length=50, verbose_name='로트번호')),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '전산등록완료')], default='pending', max_length=20, verbose_name='상태')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='전산처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_completed', to=settings.AUTH_USER_MODEL, verbose_name='전산처리자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_records', to='inventory.product', verbose_name='상품')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_registered', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '입고 기록',
                'verbose_name_plural': '입고 기록 목록',
                'db_table': 'inbound_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
