# Generated by Django 4.2.27 on 2026-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inboundrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrecord',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='inbound/%Y/%m/', verbose_name='입고 이미지'),
        ),
    ]
