# Generated by Django 4.2.27 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_uppercase_location_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='옵션코드'),
        ),
    ]
