# Generated by Django 4.2.27 on 2026-03-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_brand_brand_uq_brand_client_name'),
        ('inventory', '0012_add_option_code_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clients.brand', verbose_name='브랜드'),
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clients.client', verbose_name='거래처'),
        ),
    ]
