# Generated by Django 4.2.27 on 2026-03-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_client_brand_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 여부'),
        ),
        migrations.AddField(
            model_name='location',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='최대 적재량'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone_type',
            field=models.CharField(choices=[('INBOUND_STAGING', '입고 스테이징'), ('STORAGE', '보관존'), ('PICKING', '피킹존'), ('OUTBOUND_STAGING', '출고존'), ('DEFECT', '불량존'), ('RETURN', '반품존')], default='STORAGE', max_length=20, verbose_name='구역 유형'),
        ),
    ]
