# Generated by Django 4.2.27 on 2026-03-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_location_zone_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='product',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='CBM'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, null=True, verbose_name='규격(L/W/H)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False, verbose_name='세트상품 여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='중량(g)'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='바코드')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 바코드')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 바코드',
                'verbose_name_plural': '상품 바코드 목록',
                'db_table': 'product_barcodes',
            },
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='구성 수량')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_parents', to='inventory.product', verbose_name='구성 단품')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_children', to='inventory.product', verbose_name='세트 상품')),
            ],
            options={
                'verbose_name': '세트상품 구성',
                'verbose_name_plural': '세트상품 구성 목록',
                'db_table': 'set_products',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
