# Generated by Django 4.2.27 on 2026-03-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_wms_fields_and_config'),
        ('inventory', '0016_migrate_barcodes_to_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.IntegerField(default=0, verbose_name='실물재고')),
                ('allocated_qty', models.IntegerField(default=0, verbose_name='할당재고')),
                ('reserved_qty', models.IntegerField(default=0, verbose_name='예약재고')),
                ('lot_number', models.CharField(blank=True, default='', max_length=100, verbose_name='로트번호')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유통기한')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='clients.client', verbose_name='거래처')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.location', verbose_name='로케이션')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '재고 잔량',
                'verbose_name_plural': '재고 잔량',
                'db_table': 'inventory_balances',
                'indexes': [models.Index(fields=['client', 'product'], name='idx_balance_client_product'), models.Index(fields=['location'], name='idx_balance_location'), models.Index(fields=['client'], name='idx_balance_client')],
                'unique_together': {('product', 'location', 'client', 'lot_number')},
            },
        ),
    ]
