# Generated by Django 4.2.27 on 2026-03-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_add_wms_fields_and_config'),
        ('inventory', '0017_add_inventory_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_qty', models.IntegerField(verbose_name='예약 수량')),
                ('reason', models.CharField(max_length=200, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='해제 일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_stocks', to='clients.brand', verbose_name='브랜드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_stocks', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_stocks', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '예약재고',
                'verbose_name_plural': '예약재고',
                'db_table': 'reserved_stocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.IntegerField(verbose_name='최소 유지 수량')),
                ('alert_enabled', models.BooleanField(default=True, verbose_name='알림 활성화')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stocks', to='clients.client', verbose_name='거래처')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stocks', to='inventory.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '안전재고',
                'verbose_name_plural': '안전재고',
                'db_table': 'safety_stocks',
                'unique_together': {('product', 'client')},
            },
        ),
    ]
