# Generated by Django 4.2.27 on 2026-02-19 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_pricecontract_uq_price_contract_client_type_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('coupang', '쿠팡'), ('kurly', '컬리'), ('oliveyoung', '올리브영'), ('smartstore', '스마트스토어'), ('offline', '오프라인마트'), ('export', '해외수출'), ('other', '기타')], max_length=20, verbose_name='플랫폼')),
                ('order_number', models.CharField(max_length=100, verbose_name='발주번호')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='발주일')),
                ('status', models.CharField(choices=[('pending', '대기'), ('confirmed', '확인완료'), ('shipped', '출고완료'), ('synced', '전산반영')], default='pending', max_length=20, verbose_name='상태')),
                ('product_name', models.CharField(max_length=300, verbose_name='상품명')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='바코드')),
                ('order_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='발주수량')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='담당자')),
                ('expiry_date', models.CharField(blank=True, max_length=50, verbose_name='소비기한')),
                ('receiving_date', models.DateField(blank=True, null=True, verbose_name='입고일')),
                ('box_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='박스수량')),
                ('address', models.TextField(blank=True, verbose_name='주소지')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('platform_data', models.JSONField(blank=True, default=dict, verbose_name='플랫폼별 데이터')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인일시')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='출고일시')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='전산반영일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_orders', to='clients.client', verbose_name='거래처')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fulfillments', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='출고처리자')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='전산반영자')),
            ],
            options={
                'verbose_name': '출고 주문',
                'verbose_name_plural': '출고 주문 목록',
                'db_table': 'fulfillment_orders',
                'ordering': ['-order_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'platform'], name='idx_fulfill_client_platform'), models.Index(fields=['status'], name='idx_fulfill_status'), models.Index(fields=['order_date'], name='idx_fulfill_order_date'), models.Index(fields=['order_number'], name='idx_fulfill_order_number')],
            },
        ),
    ]
