# Generated by Django 4.2.27 on 2026-02-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_system', models.BooleanField(default=False, help_text='상태 변경 등 시스템 자동 생성 메시지 여부', verbose_name='시스템 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fulfillment.fulfillmentorder', verbose_name='출고 주문')),
            ],
            options={
                'verbose_name': '출고 주문 댓글',
                'verbose_name_plural': '출고 주문 댓글 목록',
                'db_table': 'fulfillment_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
