# Generated by Django 4.2.27 on 2026-03-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0004_platformcolumnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentcomment',
            name='file',
            field=models.FileField(blank=True, default='', help_text='이미지(JPG, PNG, GIF, WEBP) 또는 문서(PDF, Excel, Word)', upload_to='fulfillment/comments/%Y/%m/', verbose_name='첨부파일'),
        ),
    ]
