# Generated by Django 4.2.27 on 2026-03-09 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0005_fulfillmentcomment_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fulfillmentorder',
            name='idx_fulfill_order_number',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='center',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='confirmed_quantity',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='order_confirmed',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='receiving_date',
        ),
        migrations.RemoveField(
            model_name='fulfillmentorder',
            name='sku_id',
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='송장번호'),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='pallet_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='팔레트수'),
        ),
        migrations.AddField(
            model_name='fulfillmentorder',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='fulfillmentorder',
            name='box_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='박스수'),
        ),
    ]
