# Generated by Django 4.2.27 on 2026-03-12 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0006_remove_fulfillmentorder_idx_fulfill_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', '새 주문'), ('new_comment', '새 댓글'), ('status_change', '상태 변경')], max_length=20, verbose_name='알림 유형')),
                ('message', models.CharField(max_length=300, verbose_name='알림 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fulfillment.fulfillmentorder', verbose_name='관련 주문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '풀필먼트 알림',
                'verbose_name_plural': '풀필먼트 알림 목록',
                'db_table': 'fulfillment_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='idx_fulfill_notif_user_read')],
            },
        ),
    ]
