# Generated by Django 4.2.27 on 2026-03-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_add_wms_fields_and_config'),
        ('inventory', '0018_add_safety_stock_and_reserved_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생일시')),
                ('transaction_type', models.CharField(choices=[('GR', '입고'), ('GI', '출고'), ('MV', '로케이션 이동'), ('ADJ_PLUS', '재고 조정(증가)'), ('ADJ_MINUS', '재고 조정(감소)'), ('ALC', '할당'), ('ALC_R', '할당 해제'), ('RTN', '반품 입고'), ('WV_MV', '웨이브 이동')], max_length=10, verbose_name='트랜잭션 유형')),
                ('qty', models.IntegerField(verbose_name='변동 수량')),
                ('balance_after', models.IntegerField(verbose_name='변동 후 잔량')),
                ('reference_type', models.CharField(choices=[('INBOUND', '입고'), ('OUTBOUND', '출고'), ('WAVE', '웨이브'), ('ADJUSTMENT', '조정'), ('RETURN', '반품'), ('MANUAL', '수동'), ('CYCLE_COUNT', '재고실사')], max_length=20, verbose_name='참조 유형')),
                ('reference_id', models.CharField(blank=True, default='', max_length=100, verbose_name='참조번호')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='사유')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='clients.brand', verbose_name='브랜드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='clients.client', verbose_name='거래처')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='inventory.location', verbose_name='출발 로케이션')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수행자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product', verbose_name='상품')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='inventory.location', verbose_name='도착 로케이션')),
            ],
            options={
                'verbose_name': '재고 트랜잭션',
                'verbose_name_plural': '재고 트랜잭션',
                'db_table': 'inventory_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'client'], name='idx_txn_timestamp_client'), models.Index(fields=['product', 'timestamp'], name='idx_txn_product_timestamp'), models.Index(fields=['reference_type', 'reference_id'], name='idx_txn_ref_type_id'), models.Index(fields=['client', 'transaction_type', 'timestamp'], name='idx_txn_client_type_ts')],
            },
        ),
    ]
