# Generated by Django 4.2.27 on 2026-01-29 04:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('business_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='사업자등록번호 형식이 올바르지 않습니다. (예: 123-45-67890)', regex='^\\d{3}-?\\d{2}-?\\d{5}$')], verbose_name='사업자등록번호')),
                ('contact_person', models.CharField(max_length=100, verbose_name='담당자명')),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='연락처 형식이 올바르지 않습니다. (예: 010-1234-5678)', regex='^01[0-9]-?\\d{3,4}-?\\d{4}$')], verbose_name='담당자 연락처')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='담당자 이메일')),
                ('contract_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='계약 시작일')),
                ('contract_end_date', models.DateField(blank=True, help_text='미입력 시 무기한 계약으로 간주합니다.', null=True, verbose_name='계약 종료일')),
                ('invoice_email', models.EmailField(max_length=254, verbose_name='청구서 수신 이메일')),
                ('invoice_day', models.IntegerField(default=1, help_text='매월 청구서를 발송할 날짜 (1~28일)', validators=[django.core.validators.MinValueValidator(1, message='1 이상의 값을 입력하세요.'), django.core.validators.MaxValueValidator(28, message='28 이하의 값을 입력하세요.')], verbose_name='청구서 발송일')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, max_length=200, verbose_name='상세 주소')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 목록',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('INBOUND', '입고비'), ('OUTBOUND', '출고비'), ('STORAGE', '보관비'), ('DELIVERY_TINY', '택배비 - 극소(~80CM/2Kg)'), ('DELIVERY_SMALL', '택배비 - 소(~100CM/5Kg)'), ('DELIVERY_MEDIUM', '택배비 - 중(~120CM/10Kg)'), ('DELIVERY_BIG1', '택배비 - 대1(~140CM/15Kg)'), ('DELIVERY_BIG2', '택배비 - 대2(~160CM/20Kg)'), ('DELIVERY_VARIANT', '택배비 - 이형(~190CM/25Kg)'), ('DELIVERY_JEJU', '택배비 - 제주'), ('DELIVERY_REGION', '택배비 - 도서산간'), ('RETURN_TINY', '반품 - 극소(~80CM/2Kg)'), ('RETURN_SMALL', '반품 - 소(~100CM/5Kg)'), ('RETURN_MEDIUM', '반품 - 중(~120CM/10Kg)'), ('RETURN_BIG1', '반품 - 대1(~140CM/15Kg)'), ('RETURN_BIG2', '반품 - 대2(~160CM/20Kg)'), ('RETURN_VARIANT', '반품 - 이형(~190CM/25Kg)'), ('RETURN_JEJU', '반품 - 제주'), ('RETURN_REGION', '반품 - 도서산간'), ('VAS_DEFAULT', '작업비 - 기본(내품 1~3개)'), ('VAS_ADD', '작업비 - 기본 외(4개 이상)'), ('VAS_LABELING', '부가 - 라벨링'), ('VAS_REPACK', '부가 - 재포장'), ('VAS_SORTING', '부가 - 분류작업'), ('VAS_KITTING', '부가 - 키팅/세트구성'), ('VAS_RETURN', '부가 - 반품처리'), ('INV_STOCKTAKE', '재고 - 재고조사'), ('INV_CYCLE_COUNT', '재고 - 순환재고조사'), ('OTHER', '기타')], max_length=30, verbose_name='작업 유형')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('unit', models.CharField(default='건', max_length=20, verbose_name='단위')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='적용 시작일')),
                ('valid_to', models.DateField(verbose_name='적용 종료일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_contracts', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_contracts', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '단가 계약',
                'verbose_name_plural': '단가 계약 목록',
                'db_table': 'price_contracts',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['client', 'work_type', 'valid_from', 'valid_to'], name='idx_price_contract_composite')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricecontract',
            constraint=models.UniqueConstraint(fields=('client', 'work_type', 'valid_from'), name='uq_price_contract_client_type_from'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='idx_client_company_name'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['business_number'], name='idx_client_business_number'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='idx_client_is_active'),
        ),
    ]
