# Generated by Django 4.2.27 on 2026-01-28 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('business_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='사업자등록번호 형식이 올바르지 않습니다. (예: 123-45-67890)', regex='^\\d{3}-?\\d{2}-?\\d{5}$')], verbose_name='사업자등록번호')),
                ('contact_person', models.CharField(max_length=100, verbose_name='담당자명')),
                ('contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='연락처 형식이 올바르지 않습니다. (예: 010-1234-5678)', regex='^01[0-9]-?\\d{3,4}-?\\d{4}$')], verbose_name='담당자 연락처')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='담당자 이메일')),
                ('contract_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='계약 시작일')),
                ('contract_end_date', models.DateField(blank=True, help_text='미입력 시 무기한 계약으로 간주합니다.', null=True, verbose_name='계약 종료일')),
                ('invoice_email', models.EmailField(max_length=254, verbose_name='청구서 수신 이메일')),
                ('invoice_day', models.IntegerField(default=1, help_text='매월 청구서를 발송할 날짜 (1~28일)', validators=[django.core.validators.MinValueValidator(1, message='1 이상의 값을 입력하세요.'), django.core.validators.MaxValueValidator(28, message='28 이하의 값을 입력하세요.')], verbose_name='청구서 발송일')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, max_length=200, verbose_name='상세 주소')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 목록',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalletStoragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='일 단가')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='월 단가')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='적용 시작일')),
                ('valid_to', models.DateField(verbose_name='적용 종료일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_storage_prices', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pallet_prices', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '파레트 보관료',
                'verbose_name_plural': '파레트 보관료 목록',
                'db_table': 'pallet_storage_prices',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('INBOUND', '입고'), ('OUTBOUND', '출고'), ('PICKING', '피킹'), ('PACKING', '패킹'), ('LABELING', '라벨링'), ('LOADING', '상차'), ('UNLOADING', '하차'), ('INVENTORY', '재고조사'), ('SORTING', '분류작업'), ('REPACK', '재포장'), ('OTHER', '기타')], max_length=20, verbose_name='작업 유형')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('unit', models.CharField(default='건', max_length=20, verbose_name='단위')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='적용 시작일')),
                ('valid_to', models.DateField(verbose_name='적용 종료일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_contracts', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_contracts', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '단가 계약',
                'verbose_name_plural': '단가 계약 목록',
                'db_table': 'price_contracts',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['client', 'work_type', 'valid_from', 'valid_to'], name='idx_price_contract_composite')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricecontract',
            constraint=models.UniqueConstraint(fields=('client', 'work_type', 'valid_from'), name='uq_price_contract_client_type_from'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='idx_client_company_name'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['business_number'], name='idx_client_business_number'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='idx_client_is_active'),
        ),
    ]
