# Generated by Django 4.2.27 on 2026-01-29 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricecontract',
            name='uq_price_contract_client_type_from',
        ),
        migrations.AddField(
            model_name='pricecontract',
            name='item_name',
            field=models.CharField(blank=True, help_text='예: 박스, 팔레트, 20FT, 극소형 등', max_length=100, verbose_name='품목'),
        ),
        migrations.AddField(
            model_name='pricecontract',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='pricecontract',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='pricecontract',
            name='sub_category',
            field=models.CharField(blank=True, help_text='예: 화물용차, 반품검수 등', max_length=100, verbose_name='소분류'),
        ),
        migrations.AddConstraint(
            model_name='pricecontract',
            constraint=models.UniqueConstraint(fields=('client', 'work_type', 'item_name', 'valid_from'), name='uq_price_contract_client_type_item_from'),
        ),
    ]
