# Generated by Django 4.2.27 on 2026-01-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecontract',
            name='work_type',
            field=models.CharField(choices=[('INBOUND', '입고비'), ('OUTBOUND', '출고비'), ('STORAGE', '보관비'), ('DELIVERY_TINY', '택배비 - 극소(~80CM/2Kg)'), ('DELIVERY_SMALL', '택배비 - 소(~100CM/5Kg)'), ('DELIVERY_MEDIUM', '택배비 - 중(~120CM/10Kg)'), ('DELIVERY_BIG1', '택배비 - 대1(~140CM/15Kg)'), ('DELIVERY_BIG2', '택배비 - 대2(~160CM/20Kg)'), ('DELIVERY_VARIANT', '택배비 - 이형(~190CM/25Kg)'), ('DELIVERY_JEJU', '택배비 - 제주'), ('DELIVERY_REGION', '택배비 - 도서산간'), ('RETURN_TINY', '반품 - 극소(~80CM/2Kg)'), ('RETURN_SMALL', '반품 - 소(~100CM/5Kg)'), ('RETURN_MEDIUM', '반품 - 중(~120CM/10Kg)'), ('RETURN_BIG1', '반품 - 대1(~140CM/15Kg)'), ('RETURN_BIG2', '반품 - 대2(~160CM/20Kg)'), ('RETURN_VARIANT', '반품 - 이형(~190CM/25Kg)'), ('RETURN_JEJU', '반품 - 제주'), ('RETURN_REGION', '반품 - 도서산간'), ('VAS_DEFAULT', '작업비 - 기본(내품 1~3개)'), ('VAS_ADD', '작업비 - 기본 외(4개 이상)'), ('VAS_LABELING', '부가 - 라벨링'), ('VAS_REPACK', '부가 - 재포장'), ('VAS_SORTING', '부가 - 분류작업'), ('VAS_KITTING', '부가 - 키팅/세트구성'), ('VAS_RETURN', '부가 - 반품처리'), ('INV_STOCKTAKE', '재고 - 재고조사'), ('INV_CYCLE_COUNT', '재고 - 순환재고조사'), ('OTHER', '기타')], max_length=30, verbose_name='작업 유형'),
        ),
        migrations.DeleteModel(
            name='PalletStoragePrice',
        ),
    ]
