# Generated by Django 4.2.27 on 2026-02-19 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_remove_pricecontract_uq_price_contract_client_type_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='브랜드명')),
                ('code', models.CharField(blank=True, help_text='내부 관리용 코드 (선택)', max_length=50, verbose_name='브랜드 코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='clients.client', verbose_name='거래처')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드 목록',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uq_brand_client_name'),
        ),
    ]
