# Generated by Django 4.2.27 on 2026-03-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_add_carrier_stub'),
        ('clients', '0003_brand_brand_uq_brand_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='allow_cross_brand_merge',
            field=models.BooleanField(default=True, verbose_name='브랜드간 합포장 허용'),
        ),
        migrations.AddField(
            model_name='brand',
            name='packaging_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='포장 규칙'),
        ),
        migrations.AddField(
            model_name='client',
            name='allocation_rule',
            field=models.CharField(choices=[('FIFO', '선입선출'), ('LOCATION_PRIORITY', '로케이션 우선')], default='FIFO', max_length=20, verbose_name='할당 규칙'),
        ),
        migrations.AddField(
            model_name='client',
            name='allow_merge_packing',
            field=models.BooleanField(default=True, verbose_name='합포장 허용'),
        ),
        migrations.AddField(
            model_name='client',
            name='default_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_clients', to='printing.carrier', verbose_name='기본 택배사'),
        ),
        migrations.AddField(
            model_name='client',
            name='safety_stock_alert',
            field=models.BooleanField(default=True, verbose_name='안전재고 알림'),
        ),
        migrations.CreateModel(
            name='ClientWMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_auto_include', models.BooleanField(default=True, verbose_name='웨이브 자동 포함')),
                ('priority_level', models.IntegerField(default=0, help_text='숫자가 높을수록 우선 출고', verbose_name='출고 우선순위')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wms_config', to='clients.client', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '화주사 WMS 설정',
                'verbose_name_plural': '화주사 WMS 설정',
                'db_table': 'client_wms_configs',
            },
        ),
    ]
