# Generated by Django 4.2.27 on 2026-03-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INVENTORY_LEDGER', '재고원장'), ('SHIPMENT_SUMMARY', '출고요약'), ('WORKER_PRODUCTIVITY', '작업자생산성'), ('SAFETY_STOCK_ALERT', '안전재고알림')], max_length=30, verbose_name='리포트 유형')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('PROCESSING', '생성중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='상태')),
                ('params', models.JSONField(default=dict, verbose_name='조회 조건')),
                ('file', models.FileField(blank=True, default='', upload_to='reports/%Y/%m/', verbose_name='파일')),
                ('file_name', models.CharField(blank=True, default='', max_length=200, verbose_name='파일명')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='데이터 건수')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '리포트 파일',
                'verbose_name_plural': '리포트 파일',
                'db_table': 'report_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
