# Generated by Django 4.2.27 on 2026-02-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='송장번호')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='상품바코드')),
                ('scan_type', models.CharField(choices=[('송장', '송장'), ('상품', '상품')], max_length=20, verbose_name='스캔타입')),
                ('alert_code', models.CharField(choices=[('정상', '정상'), ('숫자', '숫자'), ('완료', '완료'), ('스캔오류', '스캔오류'), ('송장번호미등록', '송장번호미등록'), ('기처리배송', '기처리배송'), ('중복스캔', '중복스캔'), ('상품오류', '상품오류')], max_length=20, verbose_name='알림코드')),
                ('worker', models.CharField(blank=True, max_length=50, null=True, verbose_name='작업자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='스캔 시간')),
            ],
            options={
                'verbose_name': '검수 로그',
                'verbose_name_plural': '검수 로그 목록',
                'db_table': 'inspection_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='송장번호')),
                ('seller', models.CharField(max_length=100, verbose_name='판매처')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='수령인')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='핸드폰')),
                ('receiver_address', models.TextField(verbose_name='주소')),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('검수중', '검수중'), ('완료', '완료')], default='대기중', max_length=20, verbose_name='상태')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='검수 완료 시간')),
            ],
            options={
                'verbose_name': '송장',
                'verbose_name_plural': '송장 목록',
                'db_table': 'orders',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, verbose_name='상품바코드')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('quantity', models.IntegerField(verbose_name='주문수량')),
                ('scanned_quantity', models.IntegerField(default=0, verbose_name='스캔수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inspection.order')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
                'db_table': 'order_products',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionlog',
            index=models.Index(fields=['tracking_number'], name='inspection__trackin_a758ee_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionlog',
            index=models.Index(fields=['created_at'], name='inspection__created_c7755b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['barcode'], name='order_produ_barcode_dc87a5_idx'),
        ),
    ]
