# Generated by Django 4.2.27 on 2026-02-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='파일명')),
                ('print_order', models.CharField(blank=True, default='', max_length=100, verbose_name='출력차수')),
                ('delivery_memo', models.CharField(blank=True, default='', max_length=200, verbose_name='배송메모')),
                ('total_orders', models.IntegerField(default=0, verbose_name='송장 수')),
                ('total_products', models.IntegerField(default=0, verbose_name='상품 수')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=50, verbose_name='업로드자')),
            ],
            options={
                'verbose_name': '업로드 이력',
                'verbose_name_plural': '업로드 이력 목록',
                'db_table': 'upload_batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_memo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='배송메모'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_order',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='출력차수'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='등록일'),
        ),
        migrations.AddField(
            model_name='order',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inspection.uploadbatch', verbose_name='업로드 배치'),
        ),
    ]
