# Generated by Django 4.2.27 on 2026-03-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_uploadbatch_order_courier_order_delivery_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='file_format',
            field=models.CharField(blank=True, choices=[('eveut', '이벗'), ('cl', 'CL')], default='', max_length=10, verbose_name='양식'),
        ),
    ]
