# Generated by Django 4.2.27 on 2026-03-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_add_file_format_to_uploadbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='픽업 완료 시간'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='picked_up_by',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='픽업 작업자'),
        ),
    ]
